services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: janko
      POSTGRES_USER: janko
      POSTGRES_DB: janko
    ports:
      - 5432:5432

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      Signing_Key: "secret-test-key"
      DB_PASSWORD: janko
      DB_USERNAME: janko
      DB_DATABASE: janko
      DB_HOST: db
    ports:
      - 8080:8080
    depends_on:
     - db  
  
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8081:80
  #     - 8082:443
  
  
